2018-07-06T16:45:04.603629+00:00 app[web.1]: worker.init_process()
2018-07-06T16:45:04.603630+00:00 app[web.1]: File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 118, in init_process
2018-07-06T16:45:04.603632+00:00 app[web.1]: self.wsgi = self.app.wsgi()
2018-07-06T16:45:04.603633+00:00 app[web.1]: File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
2018-07-06T16:45:04.603635+00:00 app[web.1]: self.callable = self.load()
2018-07-06T16:45:04.603642+00:00 app[web.1]: File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
2018-07-06T16:45:04.603643+00:00 app[web.1]: return self.load_wsgiapp()
2018-07-06T16:45:04.603644+00:00 app[web.1]: File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
2018-07-06T16:45:04.603646+00:00 app[web.1]: return util.import_app(self.app_uri)
2018-07-06T16:45:04.603647+00:00 app[web.1]: File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/util.py", line 355, in import_app
2018-07-06T16:45:04.603649+00:00 app[web.1]: __import__(module)
2018-07-06T16:45:04.603650+00:00 app[web.1]: File "/app/app.py", line 98
2018-07-06T16:45:04.603652+00:00 app[web.1]: tweet_full = tweet.full_text
2018-07-06T16:45:04.603653+00:00 app[web.1]: ^
2018-07-06T16:45:04.603655+00:00 app[web.1]: IndentationError: unexpected indent
2018-07-06T16:45:04.603847+00:00 app[web.1]: [2018-07-06 16:45:04 +0000] [11] [INFO] Worker exiting (pid: 11)
2018-07-06T16:45:13.094006+00:00 app[web.1]: [2018-07-06 16:45:13 +0000] [4] [INFO] Starting gunicorn 19.3.0
2018-07-06T16:45:13.094660+00:00 app[web.1]: [2018-07-06 16:45:13 +0000] [4] [INFO] Listening at: http://0.0.0.0:36814 (4)
2018-07-06T16:45:13.094808+00:00 app[web.1]: [2018-07-06 16:45:13 +0000] [4] [INFO] Using worker: sync
2018-07-06T16:45:13.102132+00:00 app[web.1]: [2018-07-06 16:45:13 +0000] [10] [INFO] Booting worker with pid: 10
2018-07-06T16:45:13.116629+00:00 app[web.1]: [2018-07-06 16:45:13 +0000] [10] [ERROR] Exception in worker process:
2018-07-06T16:45:13.116633+00:00 app[web.1]: Traceback (most recent call last):
2018-07-06T16:45:13.116637+00:00 app[web.1]: worker.init_process()
2018-07-06T16:45:13.116635+00:00 app[web.1]: File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 507, in spawn_worker
2018-07-06T16:45:13.116638+00:00 app[web.1]: File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 118, in init_process
2018-07-06T16:45:13.116640+00:00 app[web.1]: self.wsgi = self.app.wsgi()
2018-07-06T16:45:13.116642+00:00 app[web.1]: File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
2018-07-06T16:45:13.116643+00:00 app[web.1]: self.callable = self.load()
2018-07-06T16:45:13.116645+00:00 app[web.1]: File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
2018-07-06T16:45:13.116647+00:00 app[web.1]: return self.load_wsgiapp()
2018-07-06T16:45:13.116649+00:00 app[web.1]: File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
2018-07-06T16:45:13.116650+00:00 app[web.1]: return util.import_app(self.app_uri)
2018-07-06T16:45:13.116652+00:00 app[web.1]: File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/util.py", line 355, in import_app
2018-07-06T16:45:13.116654+00:00 app[web.1]: __import__(module)
2018-07-06T16:45:13.116656+00:00 app[web.1]: File "/app/app.py", line 98
2018-07-06T16:45:13.116657+00:00 app[web.1]: tweet_full = tweet.full_text
2018-07-06T16:45:13.116659+00:00 app[web.1]: ^
2018-07-06T16:45:13.116661+00:00 app[web.1]: IndentationError: unexpected indent
2018-07-06T16:45:13.116662+00:00 app[web.1]: Traceback (most recent call last):
2018-07-06T16:45:13.116664+00:00 app[web.1]: File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 507, in spawn_worker
2018-07-06T16:45:13.116671+00:00 app[web.1]: File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
2018-07-06T16:45:13.116669+00:00 app[web.1]: self.wsgi = self.app.wsgi()
2018-07-06T16:45:13.116666+00:00 app[web.1]: worker.init_process()
2018-07-06T16:45:13.116674+00:00 app[web.1]: File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
2018-07-06T16:45:13.116668+00:00 app[web.1]: File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 118, in init_process
2018-07-06T16:45:13.116673+00:00 app[web.1]: self.callable = self.load()
2018-07-06T16:45:13.116676+00:00 app[web.1]: return self.load_wsgiapp()
2018-07-06T16:45:13.116678+00:00 app[web.1]: File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
2018-07-06T16:45:13.116679+00:00 app[web.1]: return util.import_app(self.app_uri)
2018-07-06T16:45:13.116681+00:00 app[web.1]: File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/util.py", line 355, in import_app
2018-07-06T16:45:13.116683+00:00 app[web.1]: __import__(module)
2018-07-06T16:45:13.116684+00:00 app[web.1]: File "/app/app.py", line 98
2018-07-06T16:45:13.116686+00:00 app[web.1]: tweet_full = tweet.full_text
2018-07-06T16:45:13.116688+00:00 app[web.1]: ^
2018-07-06T16:45:13.116689+00:00 app[web.1]: IndentationError: unexpected indent
2018-07-06T16:45:13.154437+00:00 app[web.1]: [2018-07-06 16:45:13 +0000] [11] [INFO] Booting worker with pid: 11
2018-07-06T16:45:13.116769+00:00 app[web.1]: [2018-07-06 16:45:13 +0000] [10] [INFO] Worker exiting (pid: 10)
2018-07-06T16:45:13.164571+00:00 app[web.1]: [2018-07-06 16:45:13 +0000] [11] [ERROR] Exception in worker process:
2018-07-06T16:45:13.164575+00:00 app[web.1]: Traceback (most recent call last):
2018-07-06T16:45:13.164581+00:00 app[web.1]: File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 507, in spawn_worker
2018-07-06T16:45:13.164582+00:00 app[web.1]: worker.init_process()
2018-07-06T16:45:13.164584+00:00 app[web.1]: File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 118, in init_process
2018-07-06T16:45:13.164586+00:00 app[web.1]: self.wsgi = self.app.wsgi()
2018-07-06T16:45:13.164588+00:00 app[web.1]: File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
2018-07-06T16:45:13.164589+00:00 app[web.1]: self.callable = self.load()
2018-07-06T16:45:13.164591+00:00 app[web.1]: File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
2018-07-06T16:45:13.164593+00:00 app[web.1]: return self.load_wsgiapp()
2018-07-06T16:45:13.164595+00:00 app[web.1]: File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
2018-07-06T16:45:13.164596+00:00 app[web.1]: return util.import_app(self.app_uri)
2018-07-06T16:45:13.164598+00:00 app[web.1]: File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/util.py", line 355, in import_app
2018-07-06T16:45:13.164600+00:00 app[web.1]: __import__(module)
2018-07-06T16:45:13.164602+00:00 app[web.1]: File "/app/app.py", line 98
2018-07-06T16:45:13.164603+00:00 app[web.1]: tweet_full = tweet.full_text
2018-07-06T16:45:13.164607+00:00 app[web.1]: IndentationError: unexpected indent
2018-07-06T16:45:13.164605+00:00 app[web.1]: ^
2018-07-06T16:45:13.164608+00:00 app[web.1]: Traceback (most recent call last):
2018-07-06T16:45:13.164610+00:00 app[web.1]: File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 507, in spawn_worker
2018-07-06T16:45:13.164612+00:00 app[web.1]: worker.init_process()
2018-07-06T16:45:13.164614+00:00 app[web.1]: File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 118, in init_process
2018-07-06T16:45:13.164615+00:00 app[web.1]: self.wsgi = self.app.wsgi()
2018-07-06T16:45:13.164617+00:00 app[web.1]: File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
2018-07-06T16:45:13.164619+00:00 app[web.1]: self.callable = self.load()
2018-07-06T16:45:13.164620+00:00 app[web.1]: File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
2018-07-06T16:45:13.164622+00:00 app[web.1]: return self.load_wsgiapp()
2018-07-06T16:45:13.164624+00:00 app[web.1]: File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
2018-07-06T16:45:13.164625+00:00 app[web.1]: return util.import_app(self.app_uri)
2018-07-06T16:45:13.164627+00:00 app[web.1]: File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/util.py", line 355, in import_app
2018-07-06T16:45:13.164630+00:00 app[web.1]: File "/app/app.py", line 98
2018-07-06T16:45:13.164629+00:00 app[web.1]: __import__(module)
2018-07-06T16:45:13.164632+00:00 app[web.1]: tweet_full = tweet.full_text
2018-07-06T16:45:13.164634+00:00 app[web.1]: ^
2018-07-06T16:45:13.164636+00:00 app[web.1]: IndentationError: unexpected indent
2018-07-06T16:45:13.164809+00:00 app[web.1]: [2018-07-06 16:45:13 +0000] [11] [INFO] Worker exiting (pid: 11)
2018-07-06T16:45:13.190120+00:00 app[web.1]: [2018-07-06 16:45:13 +0000] [4] [INFO] Shutting down: Master
2018-07-06T16:45:13.190289+00:00 app[web.1]: [2018-07-06 16:45:13 +0000] [4] [INFO] Reason: Worker failed to boot.
